CREATE TABLE `quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`quotationNumber` varchar(32) NOT NULL,
	`status` enum('draft','sent','approved','rejected','expired') NOT NULL DEFAULT 'draft',
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320),
	`customerPhone` varchar(32),
	`customerCompany` varchar(255),
	`customerCNPJ` varchar(20),
	`customerAddress` text,
	`reference` varchar(500),
	`validityDays` int NOT NULL DEFAULT 30,
	`quotationDate` varchar(10) NOT NULL,
	`notes` text,
	`items` json NOT NULL,
	`conditions` json NOT NULL,
	`texts` json NOT NULL,
	`subtotal` decimal(12,2) NOT NULL DEFAULT '0',
	`totalDiscount` decimal(12,2) NOT NULL DEFAULT '0',
	`grandTotal` decimal(12,2) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotations_quotationNumber_unique` UNIQUE(`quotationNumber`)
);
